name: Deploy Landing Zone

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Existing Password or Generate New
        id: password
        shell: bash
        run: |

          KV_NAME="kv011"
          SECRET_NAME="vm-adminPassword"

          EXISTING_PASS=$(az keyvault secret show \
            --vault-name "$KV_NAME" \
            --name "$SECRET_NAME" \
            --query value \
            -o tsv 2>/dev/null || true)

          if [ -n "$EXISTING_PASS" ]; then
            echo "Existing password found."
            ADMIN_PASS="$EXISTING_PASS"
          else
            echo "Generating new password..."

            ADMIN_PASS=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9!@#$%^&*' | head -c 20)

            az keyvault secret set \
              --vault-name "$KV_NAME" \
              --name "$SECRET_NAME" \
              --value "$ADMIN_PASS"
          fi

          echo "::add-mask::$ADMIN_PASS"
          echo "ADMIN_PASS=$ADMIN_PASS" >> $GITHUB_ENV

      - name: Deploy Infrastructure
        run: |
          az deployment sub create \
            --location eastus \
            --template-file ./bicep/main.bicep \
            --parameters ./bicep/environments/dev.bicepparam \
            --parameters adminPassword="$ADMIN_PASS"